### ISSUE TITLE
kunnen `docs` en `images` bij elkaar of hebben ze echt een ander doel?

### ISSUE THREAD

**Issue by stgm** [johnlocker/NPOGeoFinder#3]

**Comment by johnlocker** [comment]
ja, ik denk ze hebben een ander doel.  In 'docs' zitten alle documenten (ook plaatjes zoals sketches) met betrekking tot readme.md, design.md en soortgelijke documenten  waartegen in images alle images met betrekking tot code en website liggen opgelsagen. Ik move de 'images' folder naar de code folder om het duidelijk te maken.

**Comment by stgm** [comment]
Ok, sluit maar hoor.
